@apirutes = http://localhost/smartMpioApi/rutes
@token = 

###Registro de Metas
POST {{apirutes}}/metas.php

{
  "numDep": "999",
  "des_meta": "Servicio 01",
  "des_mcorta": "Servicio 01",
  "des_objetivo": "Alcanzar al Servicio 01",
  "tipo": "Servicio",
  "cuantifica": "0",
  "user":"lfrangel",
  "inicio": "2021-12-01",
  "fin": "2022-12-01"
}

###Modificar
PUT {{apirutes}}/metas.php

{
  "idmeta":"36",
  "numDep": "7",
  "des_meta": "Solicitud de Permisos para la Poda y/o Tala",
  "des_mcorta": "Permiso Poda",
  "des_objetivo": "Se realizara la cuantificacion de los permisos ",
  "tipo": "NC",
  "cuantifica": "0",
  "user":"lfrangel",
  "inicio": "2021-12-25",
  "fin": "2022-03-15",
  "edo":"1"
}

###Borrar
DELETE {{apirutes}}/metas.php

{
  "idmeta":"48",
  "user":"LFRANMGEL",
  "edo":"0"
}

###Consulta un registro
GET {{apirutes}}/metas.php?id=36&tk={{token}}

###Solicitud de Informacion por Paginacion
GET {{apirutes}}/metas.php?pag=1&e=2&tk={{token}}